package IonicEncuestasLenguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class UnaRespuestaCuatroOpciones_Constraints extends BaseConstraintsDescriptor {
  public UnaRespuestaCuatroOpciones_Constraints() {
    super(CONCEPTS.UnaRespuestaCuatroOpciones$1C);
  }

  public static class Opcion1_Property extends BasePropertyConstraintsDescriptor {
    public Opcion1_Property(ConstraintsDescriptor container) {
      super(PROPS.opcion1$9Iw7, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4693f111-d2e8-473e-8c7d-d7e82902115e(IonicEncuestasLenguage.constraints)", "107965330094989996"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return (propertyValue != null && propertyValue.length() > 0);
    }
  }
  public static class Opcion2_Property extends BasePropertyConstraintsDescriptor {
    public Opcion2_Property(ConstraintsDescriptor container) {
      super(PROPS.opcion2$9NEt, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4693f111-d2e8-473e-8c7d-d7e82902115e(IonicEncuestasLenguage.constraints)", "107965330094996164"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return (propertyValue != null && propertyValue.length() > 0);
    }
  }
  public static class Opcion3_Property extends BasePropertyConstraintsDescriptor {
    public Opcion3_Property(ConstraintsDescriptor container) {
      super(PROPS.opcion3$9NTu, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4693f111-d2e8-473e-8c7d-d7e82902115e(IonicEncuestasLenguage.constraints)", "107965330095002559"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return (propertyValue != null && propertyValue.length() > 0);
    }
  }
  public static class Opcion4_Property extends BasePropertyConstraintsDescriptor {
    public Opcion4_Property(ConstraintsDescriptor container) {
      super(PROPS.opcion4$MWj$, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4693f111-d2e8-473e-8c7d-d7e82902115e(IonicEncuestasLenguage.constraints)", "107965330095008088"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return (propertyValue != null && propertyValue.length() > 0);
    }
  }
  public static class RespuestaURCO_Property extends BasePropertyConstraintsDescriptor {
    public RespuestaURCO_Property(ConstraintsDescriptor container) {
      super(PROPS.respuestaURCO$SZMr, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:4693f111-d2e8-473e-8c7d-d7e82902115e(IonicEncuestasLenguage.constraints)", "107965330095067561"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return (propertyValue != null && propertyValue.length() > 0);
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.opcion1$9Iw7, new Opcion1_Property(this));
    properties.put(PROPS.opcion2$9NEt, new Opcion2_Property(this));
    properties.put(PROPS.opcion3$9NTu, new Opcion3_Property(this));
    properties.put(PROPS.opcion4$MWj$, new Opcion4_Property(this));
    properties.put(PROPS.respuestaURCO$SZMr, new RespuestaURCO_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept UnaRespuestaCuatroOpciones$1C = MetaAdapterFactory.getConcept(0xf5e16b511bd46e4L, 0x94b097bcd9688f43L, 0x17f91e54c5e9214L, "IonicEncuestasLenguage.structure.UnaRespuestaCuatroOpciones");
  }

  private static final class PROPS {
    /*package*/ static final SProperty opcion1$9Iw7 = MetaAdapterFactory.getProperty(0xf5e16b511bd46e4L, 0x94b097bcd9688f43L, 0x17f91e54c5e9214L, 0x17f91e54c5e9215L, "opcion1");
    /*package*/ static final SProperty opcion2$9NEt = MetaAdapterFactory.getProperty(0xf5e16b511bd46e4L, 0x94b097bcd9688f43L, 0x17f91e54c5e9214L, 0x17f91e54c5e9216L, "opcion2");
    /*package*/ static final SProperty opcion3$9NTu = MetaAdapterFactory.getProperty(0xf5e16b511bd46e4L, 0x94b097bcd9688f43L, 0x17f91e54c5e9214L, 0x17f91e54c5e9217L, "opcion3");
    /*package*/ static final SProperty opcion4$MWj$ = MetaAdapterFactory.getProperty(0xf5e16b511bd46e4L, 0x94b097bcd9688f43L, 0x17f91e54c5e9214L, 0x17f91e54c5e956cL, "opcion4");
    /*package*/ static final SProperty respuestaURCO$SZMr = MetaAdapterFactory.getProperty(0xf5e16b511bd46e4L, 0x94b097bcd9688f43L, 0x17f91e54c5e9214L, 0x17f91e54c5fa908L, "respuestaURCO");
  }
}
